'use client'
/* eslint-disable react/no-unescaped-entities */

import { X } from 'lucide-react'

interface PrivacyPolicyModalProps {
  isOpen: boolean
  onClose: () => void
}

export default function PrivacyPolicyModal({ isOpen, onClose }: PrivacyPolicyModalProps) {
  if (!isOpen) return null

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black bg-opacity-50" onClick={onClose}>
      <div className="bg-white rounded-lg max-w-4xl w-full max-h-[90vh] overflow-hidden flex flex-col" onClick={(e) => e.stopPropagation()}>
        {/* Header */}
        <div className="sticky top-0 bg-primary text-white px-6 py-4 flex items-center justify-between border-b">
          <h2 className="text-2xl font-bold">Notice of Privacy Practices</h2>
          <button onClick={onClose} className="text-white hover:text-gray-200 transition">
            <X className="w-6 h-6" />
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto px-6 py-6">
          <div className="prose prose-sm max-w-none">
            {/* Important Notice */}
            <div className="bg-blue-50 border-l-4 border-blue-500 p-4 mb-6">
              <p className="text-sm text-blue-900 font-medium">
                THIS NOTICE DESCRIBES HOW MEDICAL INFORMATION ABOUT YOU MAY BE USED AND DISCLOSED AND HOW YOU CAN GET ACCESS TO THIS INFORMATION. PLEASE REVIEW IT CAREFULLY.
              </p>
            </div>

            {/* Introduction */}
            <p className="text-gray-700 mb-4">
              This Notice of Privacy Practices is provided to you pursuant to the Health Insurance Portability and Accountability Act of 1996 and its implementing regulations ("HIPAA"), as amended. It is designed to tell you how we may, under federal law, use or disclose your medical information.
            </p>

            {/* Who Will Follow This Notice */}
            <h3 className="text-xl font-bold text-primary mt-6 mb-3">WHO WILL FOLLOW THIS NOTICE</h3>
            <p className="text-gray-700 mb-3">This notice describes Holy Name Medical Center's privacy practices and that of:</p>
            <ul className="list-disc pl-6 mb-4 text-gray-700 space-y-1">
              <li>Any health care professional authorized to enter information into your Medical Center chart.</li>
              <li>All departments and units of the Medical Center.</li>
              <li>Any member of a volunteer group we allow to help you while you are in the Medical Center.</li>
              <li>All employees, staff and other Medical Center personnel.</li>
              <li>The Physicians in our Radiology and Pathology Departments and Emergency Room and the staff in the Multiple Sclerosis Center will follow the terms of this privacy notice. In addition, they may share medical information with each other and the Medical Center for treatment, payment or Medical Center operations purposes described in this notice.</li>
            </ul>

            {/* Our Commitment */}
            <h3 className="text-xl font-bold text-primary mt-6 mb-3">OUR COMMITMENT TO YOUR PRIVACY</h3>
            <p className="text-gray-700 mb-4">
              We are committed to protecting the privacy of your health information that is collected during your medical treatment at the Medical Center. This notice applies to all of the records of your care generated by the Medical Center during your medical care and treatment, whether made by Medical Center personnel or your personal doctor, and whether maintained in paper or electronic form. Your personal doctor may have different policies or notices regarding the doctor's use and disclosure of your medical information created in the doctor's office.
            </p>
            <p className="text-gray-700 mb-4">
              This notice will tell you about the ways in which we may use and disclose medical information about you and how other health care providers may access medical information about you electronically through the Jersey Health Connect Health Information Exchange (the "HIE") unless you Opt-Out of participating in the HIE as described below under the heading "Your Rights Regarding Medical Information About You" and the subheading "Right to Request Restrictions". We also describe your rights and certain obligations we have regarding the use and disclosure of your medical information.
            </p>

            {/* Our Duties */}
            <h3 className="text-xl font-bold text-primary mt-6 mb-3">OUR DUTIES TO YOU</h3>
            <p className="text-gray-700 mb-3">We are required by law to:</p>
            <ul className="list-disc pl-6 mb-4 text-gray-700 space-y-1">
              <li>make sure that medical information that identifies you is kept private;</li>
              <li>give you this notice of our legal duties and privacy practices with respect to medical information about you;</li>
              <li>follow the terms of the HIPAA notice that is currently in effect; and</li>
              <li>notify you if a breach occurs of your unsecured medical information and inform you of any steps that you may need to take to protect yourself.</li>
            </ul>

            {/* How We May Use Information */}
            <h3 className="text-xl font-bold text-primary mt-6 mb-3">HOW WE MAY USE AND DISCLOSE MEDICAL INFORMATION ABOUT YOU UNDER HIPAA</h3>
            
            <p className="text-gray-700 mb-4 font-semibold">
              We may use or disclose your medical information for purposes of Treatment, Payment or Healthcare Operations Without Obtaining your Prior Authorization.
            </p>
            <p className="text-gray-700 mb-4">
              The following categories describe different ways that we use and disclose your medical information. For each category of uses or disclosures we will explain what we mean and try to give some examples. Not every use or disclosure in a category will be listed. However, all of the ways we are permitted to use and disclose your medical information will fall within one of the categories.
            </p>

            <h4 className="text-lg font-semibold text-gray-900 mt-4 mb-2">For Treatment:</h4>
            <p className="text-gray-700 mb-4">
              We may use medical information about you to provide you with medical treatment or services. We may disclose medical information about you to doctors, nurses, technicians, nursing and other students in training, or other Medical Center personnel who are involved in taking care of you at the Medical Center. For example, a doctor treating you for a broken leg may need to know if you have diabetes because diabetes may slow the healing process. In addition, the doctor may need to tell the dietitian if you have diabetes so that we can arrange for appropriate meals. Different departments of the Medical Center also may share medical information about you in order to coordinate the different things you need, such as prescriptions, lab work and x-rays. We may also disclose medical information about you to people outside the Medical Center who may be involved in your medical care after you leave the Medical Center, such as clergy or others we use to provide services that are part of your care.
            </p>
            <p className="text-gray-700 mb-4">
              In addition, the Medical Center participates in the Jersey Health Connect HIE, which allows your medical information to be shared electronically with any authorized health care provider who participates in the Jersey Health Connect HIE. Your electronic medical record will be included in the Jersey Health Connect HIE and pertinent medical information contained therein will be accessed by other Jersey Health Connect HIE participants, as needed, to provide treatment to you unless you "Opt-Out" as described below under the heading "Your Rights Regarding Medical Information About You" and the sub-heading "Right to Request Restrictions". For instance, if you receive a blood test from one provider participating in the Jersey Health Connect HIE network but then are treated by a different provider in the Jersey Health Connect HIE network, both of your treating providers can share your test result electronically through the secure Jersey Health Connect HIE network, as long as they are otherwise authorized to do so. On the other hand, if you Opt-Out of the Jersey Health Connect HIE, your medical information will continue to be used, accessed and released as needed to provide treatment to you, but will not be made electronically available for such purpose through the Jersey Health Connect HIE.
            </p>

            <h4 className="text-lg font-semibold text-gray-900 mt-4 mb-2">For Payment:</h4>
            <p className="text-gray-700 mb-4">
              We may use and disclose medical information about you so that the treatment and services you receive at the Medical Center may be billed to and payment may be collected from you, an insurance company or a third party. For example, we may need to give your health plan information about surgery you received at the Medical Center so your health plan will pay us or reimburse you for the surgery. We may also tell your health plan about a treatment you are going to receive to obtain prior approval or to determine whether your plan will cover the treatment. Your own physician and other physicians who provide treatment such as emergency room care, reading x-rays or reading pathology specimens may also use your information for their billing purposes.
            </p>

            <h4 className="text-lg font-semibold text-gray-900 mt-4 mb-2">For Health Care Operations:</h4>
            <p className="text-gray-700 mb-4">
              We may use and disclose medical information about you for Medical Center operations. These uses and disclosures are necessary to run the Medical Center and make sure that all of our patients receive quality care. Your medical information will be provided to third party "business associates" that perform various activities and services (e.g. billing, transcription, and operating and troubleshooting our health information technology) on our behalf. In such situations, we will have a written contract in place that restricts the ability of the business associate to use or disclose your medical information except in accordance with HIPAA requirements. For example, we may use medical information to review our treatment and services and to evaluate the performance of our staff in caring for you. We may also combine medical information about many Medical Center patients to decide what additional services the Medical Center should offer, what services are not needed, and whether certain new treatments are effective. We may also disclose information to doctors, nurses, technicians, students, and other Medical Center personnel for review and learning purposes. We may also combine the medical information we have with medical information from other medical centers to compare how we are doing and see where we can make improvements in the care and services we offer. We may remove information that identifies you from this set of medical information so others may use it to study health care and health care delivery without learning who the specific patients are.
            </p>

            <h4 className="text-lg font-semibold text-gray-900 mt-4 mb-2">Your Medical Information Will Also be Used Without Prior Authorization Under the Following Circumstances:</h4>
            
            <p className="text-gray-700 mb-2"><strong>Appointment Reminders:</strong> We may use and disclose medical information to contact you as a reminder that you have an appointment for treatment or medical care at the Medical Center.</p>

            <p className="text-gray-700 mb-2"><strong>Treatment Alternatives:</strong> We may use and disclose medical information to tell you about or recommend possible treatment options or alternatives that may be of interest to you.</p>

            <p className="text-gray-700 mb-2"><strong>Health-Related Benefits and Services:</strong> We may use and disclose medical information to tell you about health-related benefits or services that may be of interest to you.</p>

            <p className="text-gray-700 mb-2"><strong>Fundraising Activities:</strong> We may use certain information about you to contact you in an effort to raise money for the Medical Center and its programs and operations. We may disclose certain information to Holy Name Medical Center Foundation, so that the Foundation may contact you in raising money for the Medical Center. If you do not want the Medical Center to contact you for fundraising efforts, you must notify the Executive Director, Holy Name Medical Center Foundation, at 718 Teaneck Road, Teaneck, New Jersey 07666, in writing.</p>

            <p className="text-gray-700 mb-2"><strong>Medical Center Directory:</strong> Unless you disagree or object, we may include certain limited information about you in the Medical Center directory while you are a patient at the Medical Center. This information may include your name and your religious affiliation. The directory information, except for your religious affiliation, may also be released to people who ask for you by name. Your religious affiliation may be given to a member of the clergy, such as a priest or rabbi, even if they don't ask for you by name. This is so your family, friends and clergy can visit you in the Medical Center and generally know how you are doing.</p>

            <p className="text-gray-700 mb-2"><strong>Individuals Involved in Your Care or Payment for your Care:</strong> Unless you disagree or object, we may release medical information about you to a friend or family member who is involved in your medical care or to someone who helps pay for your care. We may also tell your family or friends your condition and that you are in the Medical Center. In addition, we may disclose medical information about you to an entity assisting in a disaster relief effort so that your family can be notified about your condition, status and location. If you are unable or unavailable to agree or object to our discussing these matters with your family and/or friends, our health professionals will use judgment as to whether any communications with your family or others involved in your care are necessary and/or appropriate.</p>

            <p className="text-gray-700 mb-2"><strong>Research:</strong> Under certain circumstances, we may use and disclose medical information about you for research purposes. For example, a research project may involve comparing the health and recovery of all patients who received one medication to those who received another, for the same condition. All research projects, however, are subject to a special approval process. This process evaluates a proposed research project and its use of medical information, trying to balance the research needs with patients' need for privacy of their medical information. Before we use or disclose medical information for research, the project will have been approved through this research approval process, but we may, however, disclose medical information about you to people preparing to conduct a research project, for example, to help them look for patients with specific medical needs, so long as the medical information they review does not leave the Medical Center. We will ask for your specific permission if the researcher will have access to your name, address or other information that reveals who you are, or will be involved in your care at the Medical Center.</p>

            <p className="text-gray-700 mb-2"><strong>As Required By Law:</strong> We will disclose medical information about you when required to do so by federal, state or local law.</p>

            <p className="text-gray-700 mb-4"><strong>To Avert a Serious Threat to Health or Safety:</strong> We may use and disclose medical information about you when necessary to prevent or lessen a serious and imminent threat to your health and safety or the health and safety of the public or another person. Any disclosure, however, would only be to someone able to help prevent the threat.</p>

            {/* Special Situations */}
            <h3 className="text-xl font-bold text-primary mt-6 mb-3">SPECIAL SITUATIONS</h3>
            
            <p className="text-gray-700 mb-2"><strong>Organ and Tissue Donation:</strong> We are required to release medical information about patients who die in the Medical Center to organizations that handle organ procurement or organ, eye or tissue transplantation or to an organ donation bank, as necessary to facilitate organ or tissue donation and transplantation.</p>

            <p className="text-gray-700 mb-2"><strong>Military and Veterans:</strong> If you are a member of the armed forces, we may release medical information about you as required by military command authorities. We may also release medical information about foreign military personnel to the appropriate foreign military authority.</p>

            <p className="text-gray-700 mb-2"><strong>Workers' Compensation:</strong> We may release medical information about you for workers' compensation or similar programs. These programs provide benefits for work-related injuries or illnesses.</p>

            <p className="text-gray-700 mb-2"><strong>Public Health Purposes:</strong> We may disclose medical information about you to local, state or federal authorities, agencies or other entities, as authorized or required by law, for public health purposes, which may include the following:</p>
            <ul className="list-disc pl-6 mb-4 text-gray-700 space-y-1">
              <li>to prevent or control disease, injury or disability;</li>
              <li>to report births and deaths;</li>
              <li>to report child abuse or neglect;</li>
              <li>to report reactions to medications or problems with products;</li>
              <li>to notify people of recalls of products they may be using;</li>
              <li>to notify a person who may have been exposed to a communicable disease or may be at risk for contracting or spreading a disease or condition;</li>
              <li>to notify the appropriate government authority if we believe a patient has been the victim of abuse, neglect or domestic violence. We will only make this disclosure if you agree or when required or authorized by law.</li>
            </ul>

            <p className="text-gray-700 mb-2"><strong>Health Oversight Activities:</strong> We may disclose medical information to a health oversight agency for activities authorized by law. These oversight activities include, for example, audits, investigations, inspections, and licensure. These activities are necessary for the government to monitor the health care system, government programs, and compliance with civil rights laws.</p>

            <p className="text-gray-700 mb-2"><strong>Lawsuits and Disputes:</strong> If you are involved in a lawsuit or a dispute, we may disclose medical information about you in response to a court or administrative order. We may also disclose medical information about you in response to a subpoena, discovery request, or other lawful process by someone else involved in the dispute, with your authorization.</p>

            <p className="text-gray-700 mb-2"><strong>Law Enforcement:</strong> We may release medical information if asked to do so by a law enforcement official:</p>
            <ul className="list-disc pl-6 mb-4 text-gray-700 space-y-1">
              <li>In response to a court order, subpoena, warrant, summons or similar process;</li>
              <li>To identify or locate a suspect, fugitive, material witness, or missing person;</li>
              <li>About the victim of a crime if, under certain limited circumstances, we are unable to obtain the person's agreement;</li>
              <li>About a death we believe may be the result of criminal conduct;</li>
              <li>About criminal conduct at the Medical Center; and</li>
              <li>In emergency circumstances to report a crime; the location of the crime or victims; or the identity, description or location of the person who committed the crime.</li>
            </ul>

            <p className="text-gray-700 mb-2"><strong>Coroners, Medical Examiners and Funeral Directors:</strong> We may release medical information to a coroner or medical examiner. This may be necessary, for example, to identify a deceased person or determine the cause of death. We may also release medical information about patients of the Medical Center to funeral directors as necessary to carry out their duties.</p>

            <p className="text-gray-700 mb-2"><strong>National Security and Intelligence Activities:</strong> We may release medical information about you to authorized federal officials for intelligence, counterintelligence, and other national security activities authorized by law.</p>

            <p className="text-gray-700 mb-2"><strong>Protective Services for the President and Others:</strong> We may disclose medical information about you to authorized federal officials so they may provide protection to the President, other authorized persons or foreign heads of state or conduct special investigations.</p>

            <p className="text-gray-700 mb-2"><strong>Inmates:</strong> If you are an inmate of a correctional institution or under the custody of a law enforcement official, we may release medical information about you to the correctional institution or law enforcement official. This release would be necessary (1) for the institution to provide you with health care; (2) to protect your health and safety or the health and safety of others; or (3) for the safety and security of the correctional institution.</p>

            <p className="text-gray-700 mb-2"><strong>Health Information Exchange (HIE):</strong> Holy Name Medical Center and other health care providers participate in the Jersey Health Connect HIE which allows patient information to be shared electronically through a secured connected network. The HIE allows for immediate electronic access to your health care providers who participate in the Jersey Health Connect HIE network to your pertinent medical information necessary for treatment, payment and certain health care operations. If you have not Opted-Out of the Jersey Health Connect HIE, your information will be available through the Jersey Health Connect HIE network to your authorized participating health care providers in accordance with this Notice of Privacy Practices and the law. If you do Opt-Out of the Jersey Health Connect HIE, your medical information will continue to be used in accordance with this HIPAA Notice and the law, but will not be made electronically available through the Jersey Health Connect HIE.</p>

            <p className="text-gray-700 mb-4"><strong>Required Uses and Disclosures:</strong> Under the law, disclosures must be made to you, upon your request (unless medically contraindicated) and when required by the Secretary of the Department of Health and Human Services to investigate or to determine compliance with HIPAA.</p>

            <h4 className="text-lg font-semibold text-gray-900 mt-4 mb-2">Uses and Disclosures with Your Authorization</h4>
            <p className="text-gray-700 mb-4">
              For all other circumstances not described in section 1 above, we may only use or disclose your medical information where (1) you have signed an authorization on our authorization form or (2) such use or disclosure is consistent with the general consent that you signed upon admission. If you authorize us to use or disclosure your medical information for another purpose, you may revoke your authorization in writing at any time. However, the revocation will not be effective to the extent that we have taken action in reliance on the use or disclosure allowed by the authorization. We generally must obtain your prior authorization for the following uses and disclosures of your medical information:<br/>
              (i) Psychotherapy Notes (however, we may use and disclose psychotherapy notes for treatment, payment or health care operations without authorization or as otherwise permitted or required by law);<br/>
              (ii) marketing activities or communications (however, we may send you communications that relate to your treatment, case management or care coordination); and<br/>
              (iii) activities where we receive money in exchange for your medical information, except where related to the treatment you receive, public health, or research purposes.
            </p>

            <p className="text-gray-700 mb-4"><strong>Mobile Information and Usage:</strong> No mobile information will be shared with third parties/affiliates for marketing/promotional purposes. All other categories exclude text messaging originator opt-in data and consent; this information will not be shared with any third parties.</p>

            {/* Your Rights */}
            <h3 className="text-xl font-bold text-primary mt-6 mb-3">YOUR RIGHTS REGARDING MEDICAL INFORMATION ABOUT YOU</h3>
            <p className="text-gray-700 mb-4">You have the following rights regarding medical information we maintain about you:</p>
            
            <h4 className="text-lg font-semibold text-gray-900 mt-4 mb-2">Right to Inspect and Copy:</h4>
            <p className="text-gray-700 mb-4">
              You have the limited right to inspect and copy medical information that may be used to make decisions about your care, unless such inspection is determined to be medically contraindicated. Usually, this includes medical and billing records, but does not include psychotherapy notes.
            </p>
            <p className="text-gray-700 mb-4">
              If such medical information is maintained in an Electronic Designated Record Set (as hereinafter defined), your access rights include the right to a copy in electronic format. We will charge you a reasonable fee for the copying of paper records, and in the case of a request for an electronic copy of your medical information maintained in an Electronic Designated Record Set (or a summary or explanation of such information) we may charge you the amount of our labor costs in responding to your request. A "Designated Record Set" is the HIPAA term for medical and billing records and any other records that we use for making health care decisions about you. Your right to inspect and obtain a copy of your medical information extends only to your medical information contained in the Designated Record Set, whether electronic or otherwise, that we maintain for you.
            </p>
            <p className="text-gray-700 mb-4">
              To inspect and copy your medical information that is contained in the Designated Record Set, you must submit your request in writing to the Director of Health Information Services at Holy Name Medical Center, 718 Teaneck Road, Teaneck, New Jersey 07666.
            </p>
            <p className="text-gray-700 mb-4">
              We may deny your request to inspect and copy in certain very limited circumstances. If you are denied access to medical information, you may request that the denial be reviewed. Another licensed health care professional chosen by the Medical Center will review your request and the denial. The person conducting the review will not be the person who denied your request. We will comply with the outcome of the review.
            </p>
            <p className="text-gray-700 mb-4">
              You should take note that, if you are a parent or legal guardian of a minor, certain portions of the minor's medical record will not be accessible to you in accordance with applicable law (for example, records relating to pregnancy, venereal disease, substance use and abuse, and HIV/AIDS).
            </p>

            <h4 className="text-lg font-semibold text-gray-900 mt-4 mb-2">Right to Request to Amend:</h4>
            <p className="text-gray-700 mb-4">
              If you feel that medical information we have about you is incorrect or incomplete, you may ask us to amend the information. You have the right to request an amendment for as long as the information is kept by or for the Medical Center.
            </p>
            <p className="text-gray-700 mb-4">
              To request an amendment, your request must be made in writing and submitted to the Director of Health Information Services at the Medical Center's address. In addition, you must provide a reason that supports your request.
            </p>
            <p className="text-gray-700 mb-3">We may deny your request if you ask us to amend information that:</p>
            <ul className="list-disc pl-6 mb-4 text-gray-700 space-y-1">
              <li>Is accurate and complete;</li>
              <li>Was not created by us, unless the person or entity that created the information is no longer available to make the amendment;</li>
              <li>Is not part of the medical information kept by or for the Medical Center; or</li>
              <li>Is not part of the information which you would be permitted to inspect and copy.</li>
            </ul>

            <h4 className="text-lg font-semibold text-gray-900 mt-4 mb-2">Right to an Accounting of Disclosures:</h4>
            <p className="text-gray-700 mb-4">
              You have the right to request an "accounting of disclosures". This is a list of the disclosures we made of medical information about you.
            </p>
            <p className="text-gray-700 mb-4">
              To request this list or accounting of disclosures, you must submit your request in writing to the Director of Health Information Services. Your request must state a time period, which may not be longer than six years and may not include dates before April 14, 2003. The right to receive an accounting is subject to certain other exceptions, restrictions and limitations.
            </p>
            <p className="text-gray-700 mb-4">
              Your request should indicate in what form you want the list (for example, on paper, electronically). The first list you request within a 12-month period will be free. For additional lists, we may charge you the costs of providing the list. We will notify you of the cost involved and you may choose to withdraw or modify your request at that time before any costs are incurred by the Medical Center.
            </p>

            <h4 className="text-lg font-semibold text-gray-900 mt-4 mb-2">Right to Request Restrictions:</h4>
            <p className="text-gray-700 mb-4">
              You have the right to request a restriction on the uses and disclosures of your medical information for treatment, payment or health care operations. You also have the right to request a limit on the medical information we disclose about you to someone who is involved in your care or the payment for your care, like a family member or friend. For example, you could ask that we not use or disclose information about a surgery you had.
            </p>
            <p className="text-gray-700 mb-4">
              While we will consider all requests for restrictions carefully, we are not required to agree to your request unless you are asking us to restrict the use and disclosure of your medical information to a health plan for payment or health care operation purposes and such information you wish to restrict pertains solely to a health care item or service for which you have paid us "out-of-pocket" in full.
            </p>
            <p className="text-gray-700 mb-4">
              To request restrictions, you must make your request in writing to the Director of Health Information Services at the Medical Center's address. In your request, you must tell us (1) what information you want to limit; (2) whether you want to limit our use, disclosure or both; and (3) to whom you want the limits to apply, for example, disclosures to your spouse.
            </p>

            <h4 className="text-lg font-semibold text-gray-900 mt-4 mb-2">Right to Opt-Out of Jersey Health Connect HIE:</h4>
            <p className="text-gray-700 mb-4">
              With regard to the Jersey Health Connect HIE only, if you do not wish to allow otherwise authorized doctors, nurses and other clinicians involved in your care to electronically share your medical information with one another through the Jersey Health Connect HIE as explained in this HIPAA Notice, you can complete, sign and submit the Jersey Health Connect HIE Opt-Out form to your provider as instructed on that form, and any Opt-Out selection that you make will be honored. The Jersey Health Connect HIE Opt-Out form can be obtained directly from any of your providers participating in the Jersey Health Connect HIE, or you can download the form from jerseyhealthconnect.org. If you Opt-Out of the Jersey Health Connect HIE, your medical information will continue to be accessed, used and released, electronically or otherwise, as needed to provide treatment to you, but it will not be made available for such purpose through the Jersey Health Connect HIE network.
            </p>

            <h4 className="text-lg font-semibold text-gray-900 mt-4 mb-2">Right to Request Confidential Communications:</h4>
            <p className="text-gray-700 mb-4">
              You have the right to request that we communicate with you about medical matters in a certain way or at a certain location. For example, you can ask that we only contact you at work or by mail.
            </p>
            <p className="text-gray-700 mb-4">
              To request confidential communications, you must make your request in writing to the Director of Health Information Services at the Medical Center's address. We will not ask you the reason for your request. We will accommodate all reasonable requests. Your request must specify how or where you wish to be contacted.
            </p>

            <h4 className="text-lg font-semibold text-gray-900 mt-4 mb-2">Right to a Paper Copy of This Notice:</h4>
            <p className="text-gray-700 mb-4">
              You have the right to a paper copy of this notice. You may ask us to give you a copy of this notice at any time. Even if you have agreed to receive this notice electronically, you are still entitled to a paper copy of this notice.
            </p>
            <p className="text-gray-700 mb-4">
              You may obtain a copy of this notice at our website, www.holyname.org/policy.
            </p>
            <p className="text-gray-700 mb-4">
              To obtain a paper copy of this notice, or if you would like to exercise one or more of these rights, contact the Director of Health Information Services at the Medical Center, 718 Teaneck Road, Teaneck, New Jersey 07666, 201-833-3155.
            </p>

            {/* Changes to This Notice */}
            <h3 className="text-xl font-bold text-primary mt-6 mb-3">CHANGES TO THIS NOTICE</h3>
            <p className="text-gray-700 mb-4">
              We reserve the right to change this notice. We reserve the right to make the revised or changed notice effective for medical information we already have about you as well as any information we receive in the future. We will post a copy of the current notice in the Medical Center and on our website at www.holyname.org/policy. The notice will contain on the first page, in the top right hand corner, the current effective date. In addition, each time you register at or are admitted to the Medical Center for treatment or health care services as an inpatient or outpatient, we will offer you a copy of the current notice in effect.
            </p>

            {/* Complaints */}
            <h3 className="text-xl font-bold text-primary mt-6 mb-3">COMPLAINTS ABOUT OUR PRIVACY PRACTICES</h3>
            <p className="text-gray-700 mb-4">
              If you believe your privacy rights have been violated, you may file a written complaint with the Medical Center or with the Office of Civil Rights (OCR) for the New Jersey region. You may contact the OCR at: Office for Civil Rights, Jacob Javits Federal Building, 26 Federal Plaza-Suite 3312, New York, New York 10278, 212-264-2355. To file a complaint with the Medical Center, contact the Director of Health Information Services at the Medical Center's address.
            </p>
            <p className="text-gray-700 mb-4">
              You will not be retaliated against for filing a complaint.
            </p>

            {/* Contact Information */}
            <div className="bg-gray-50 border border-gray-200 rounded-lg p-4 mt-6">
              <h4 className="font-semibold text-gray-900 mb-2">Contact Information</h4>
              <p className="text-sm text-gray-700 mb-1">
                <strong>Holy Name Medical Center</strong>
              </p>
              <p className="text-sm text-gray-700 mb-1">
                718 Teaneck Road, Teaneck, NJ 07666
              </p>
              <p className="text-sm text-gray-700 mb-1">
                Phone: (201) 833-3000
              </p>
              <p className="text-sm text-gray-700">
                Director of Health Information Services: (201) 833-3155
              </p>
            </div>

            {/* Effective Date */}
            <p className="text-sm text-gray-500 italic mt-6">
              Effective Date: January 29, 2015
            </p>
          </div>
        </div>
      </div>
    </div>
  )
}
